import type { Metadata } from "next";
import { League_Spartan, Lalezar } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  weight: ["100", "400", "700"],
});
const lalezar = Lalezar({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${leagueSpartan.className} ${lalezar.className} antialiased`}
      >
        <div className="flex flex-row">
          <Navbar/>
          <div className="flex-grow">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
