import type { Metadata } from "next";
import { League_Spartan, Lalezar } from "next/font/google";
import "./globals.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  weight: ["100", "400", "700"],
});
const lalezar = Lalezar({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${leagueSpartan.className} ${lalezar.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
